---
title: siteleaf-updater
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: aterenin/minima-reboot
footer_icons:
- username: gofunky/siteleaf-updater
  url: https://github.com/gofunky/siteleaf-updater
  icon: icon-github.svg
