name: 'update siteleaf'
description: |
  update the index file of your project's siteleaf project with your repository's README.md file
inputs:
  api-key:
    description: |
      the API key that grants access to this repository's siteleaf project
    required: true
    default: ''
    format: '*'
    sensitive: true
    arg: 'api-key'
    env: 'SITELEAF_API_KEY'
  api-secret:
    description: |
      the API secret that grants access to this repository's siteleaf project
    required: true
    default: ''
    format: '*'
    sensitive: true
    arg: 'api-secret'
    env: 'SITELEAF_API_SECRET'
  site:
    description: |
      the siteleaf site id to be updated
    required: true
    default: ''
    format: 'String'
    arg: 'site'
    env: 'SITELEAF_SITE'
  page:
    description: |
      the siteleaf page path to be updated
    required: false
    default: 'index'
    format: 'String'
    arg: 'page'
    env: 'SITELEAF_PAGE'
  file:
    description: |
      the name of the local markdown file to read
    required: false
    default: 'README.md'
    format: 'String'
    arg: 'file'
    env: 'SITELEAF_MD_SOURCE'
  publish:
    description: |
      allows publishing the site after updating
    required: false
    default: false
    format: 'Boolean'
    arg: 'publish'
  help:
    description: |
      print a help message
    required: false
    default: false
    format: 'Boolean'
    arg: 'help'
outputs:
  name:
    description: 'the siteleaf page name'
runs:
  using: 'node12'
  main: 'dist/index.js'
